### ISSUE TITLE
Immediately running functions despite timeouts

### ISSUE THREAD

**Issue by serkolch** [serkolch/simon#2]
In the main.js file, I'm trying to build functionality such that the computer adds a class to a div, and after some time removes that class. It will continuously do this each round for each div from the previous round and a new random div.

- In lines 17-23 I define the functions to add and remove a class.
- In lines 26-31, I have a for loop to run functions for any divs from the previous round.
- In lines 37 and 38 I add and remove class for a new, random div. I then push that div's index into the buttonOrder array.

When running this, I'm not seeing any effect on the screen. The console logs (28 and 30) show that the class is successfully added and removed. The console log (43) shows that pushing the index into the buttonOrder array is working. 

The issue is the setTimeouts. When I try to only addClass, the effect happens immediately. When I change my counter-based time-delay from (i*1250) to a fixed 1250, the effect still happens immediately.

Please advise

**Comment by serkolch** [comment]
It's probably closures, but I still need assistance. Working to fix on my own, if I finish it I'll close this issue out.

**Comment by sungchoi** [comment]
```javascript
  // Add the class with the intended effect
    var addEffect = function(index) {
      $squares.eq(index).addClass('center');
    }
  //Remove the intended effect
    var removeEffect = function(index) {
      $squares.eq(index).removeClass('center');
    }

  //Loop through an array of the random choices from previous rounds and set a timeout for adding and removing effects 
    for (i=0;i<buttonOrder.length;i++){
      window.setTimeout(addEffect(buttonOrder[i]),(i*1250));
      console.log($squares)
      window.setTimeout(removeEffect(buttonOrder[i]),((i*1250)+4000));
      console.log($squares)
    }
```

Two things pop out at me:
setTimeout expects a function as the first argument. What are you currently giving it right now? Hint, it's not a function.
Secondly, yes, you do need a closure, a function that returns the function that you want the timer to run, as well. Does that make sense?

**Comment by serkolch** [comment]
Yea I realize that by giving the function inside the setTimeout a () & input, it now returns the inside of the function instead of having a function as input. Fixing that is the issue now.

**Comment by sungchoi** [comment]
Close this issue if you figure it out. Otherwise, send me a follow up comment.

**Comment by serkolch** [comment]
How long do you recommend that I work on this before following up? I've been at this for over an hour now.

**Comment by serkolch** [comment]
I can't even get the non-forLoop setTimeout to work, which is the first visible action the screen is supposed to show

**Comment by serkolch** [comment]
I finally fixed it. Changed the functions to:
    var addEffect = function(x) {
      return function() {
        $squares.eq(x).addClass('center');
      };
    };

**Comment by sungchoi** [comment]
Closures to the rescue!

**Comment by sungchoi** [comment]
Follow up whenever you need. I just can't promise how quickly we'll be able to respond.
