### ISSUE TITLE
Mixing JQuery & Javascript

### ISSUE THREAD

**Issue by serkolch** [serkolch/simon#3]
I have the following lines to make the user click on squares for simon says:
```
    var clickQuadrant = function(event) {
        var target = event.target;
        target.classList.add('animated','pulse');
        window.setTimeout(function() {
          target.classList.remove('animated','pulse');
        }, 1500)
    }
```

In the rest of my document, I've been using JQuery, but I couldn't get target.addClass('animated pulse') to work, as it said it was not a function. JQuery API shows event.target being valid JQuery.

I know we should be consistent with our style, but I just couldn't get this to work with JQuery. How do I get event.target using JQuery?

**Comment by sungchoi** [comment]
Off the top of my head I would say, just wrap it in cash, i.e. turn it into a jQueryObject:
```javascript
   var clickQuadrant = function(event) {
        var $target = $(event.target);
        //...
    }
```

**Comment by sungchoi** [comment]
I double checked the jQuery docs. The `event` should be a jQuery `event` object, but the target property returns a vanilla DOM node element, so you need to wrap it into a jQuery object. Just the way that jQuery works.
